<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="TestBootstrap.Default" %>

<!DOCTYPE html>
<html lang="en">
<head runat="server">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Product List</title>

<%--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />--%>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.css" />

    <style>
        .custom-expand-icon::before {
        content: "\2717";   /* ▉ - Unicode escape, CSS syntax */
        font-family: inherit; /* or a specific font if the glyph needs one */
    </style>

    <script src="Scripts/jquery-3.7.1.js"></script>

    <!-- Bootstrap 5 CSS (CDN) -->
<%--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />--%>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.css" rel="stylesheet" />

    <!-- bootstrap-treeview (from https://github.com/patternfly/patternfly-bootstrap-treeview)-->
    <link href="css/bootstrap-treeview.css" rel="stylesheet" />
    <script src="js/bootstrap-treeview.js"></script>

    <script>
        $(document).ready(function () {
            //alert("");
            //return;

            // "load on expand" version
            loadRootTree();
            return;

            // static tree data generated by code behind
            $.ajax({
                type: "POST",
                url: "Default.aspx/GetTreeData", // adjust to your actual page name
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    $('#tree').treeview({
                        data: response.d, // ASP.NET wraps the result in a "d" property
                        levels: 2,
                        color: "#428bca",
                        expandIcon: 'fas fa-chevron-right',
                        collapseIcon: 'fas fa-chevron-down'
                    });
                },
                error: function (err) {
                    console.error("Failed to load tree data:", err);
                }
            });
            return;

            // static tree data
            var treeData = [
                {
                    text: "Parent 1",
                    nodes: [
                        {
                            text: "Child 1",
                            nodes: [
                                { text: "Grandchild 1" },
                                { text: "Grandchild 2" }
                            ]
                        },
                        { text: "Child 2" }
                    ]
                },
                {
                    text: "Parent 2"
                },
                {
                    text: "Parent 3"
                }
            ];

            // Initialize the treeview
            $('#tree').treeview({
                data: treeData,
                levels: 2,          // Expand up to 2 levels by default
                color: "#428bca",   // Optional: text color
                expandIcon: 'fas fa-chevron-right',
                collapseIcon: 'fas fa-chevron-down'
                //    expandIcon: 'glyphicon glyphicon-chevron-right',
                //        collapseIcon: 'glyphicon glyphicon-chevron-down'
                //    expandIcon: 'glyphicon glyphicon-plus',
                //    collapseIcon: 'glyphicon glyphicon-minus'
            });
        });

        function loadRootTree() {
            $.ajax({
                type: "POST",
                url: "Default.aspx/GetRootNodes",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    $('#tree').treeview({
                        data: response.d,
                        levels: 1,
                        color: "#428bca",
                        showImage: true,
                        //
                        //expandIcon: 'fa-angle-right',
                        // "good" combination / can't commented even if we use custom icons, because no item will be expandable
                        collapseIcon: 'fa fa-angle-down',
                        expandIcon: 'fas fa-chevron-right',
                        //
                        //collapseIcon: 'fas fa-chevron-down',
                        emptyIcon: 'custom-expand-icon',
                        lazyLoad: function (node, render) {
                            $.ajax({
                                type: "POST",
                                url: "Default.aspx/GetChildNodes",
                                contentType: "application/json; charset=utf-8",
                                dataType: "json",
                                data: JSON.stringify({ parentId: node.id }),
                                success: function (childResponse) {
                                    render(childResponse.d);
                                },
                                error: function (xhr) {
                                    console.error("Failed to load children:", xhr.responseText);
                                }
                            });
                        }
                    });
                },
                error: function (xhr) {
                    console.error("Failed to load root nodes:", xhr.responseText);
                }
            });
        }
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container mt-4">
            <div class="container mt-4">
                <h2>Simple Treeview</h2>
                <!-- The container where the tree will render -->
                <div id="tree"></div>
            </div>
            <h2 class="mb-3">Product Inventory (HTML Table)</h2>

            <!-- 
                THE BOOTSTRAP HTML TABLE 
                The <asp:Repeater> will generate the <tr> rows for us.
            -->
            <div class="table-responsive">
                <table class="table table-striped table-hover table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>ID</th>
                            <th>Product Name</th>
                            <th>Category</th>
                            <th class="text-end">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- The Repeater control binds to our C# data -->
                        <asp:Repeater ID="rptProducts" runat="server">
                            <ItemTemplate>
                                <tr>
                                    <td><%# Eval("ID") %></td>
                                    <td><%# Eval("Name") %></td>
                                    <td>
                                        <span class="badge bg-secondary"><%# Eval("Category") %></span>
                                    </td>
                                    <td class="text-end fw-bold"><%# Eval("Price", "{0:C}") %></td>
                                </tr>
                            </ItemTemplate>
<%--                            <!-- Optional: Show a message if the data source is empty -->
                            <EmptyDataTemplate>
                                <tr>
                                    <td colspan="4" class="text-center text-muted">No products found.</td>
                                </tr>
                            </EmptyDataTemplate>--%>
                        </asp:Repeater>
                    </tbody>
                </table>
            </div>
        </div>
        <hr />
        <div class="container mt-4">
            <h2 class="mb-3">Product Inventory (GridView)</h2>

            <!-- 
                THE BOOTSTRAP HTML TABLE 
                The <asp:Repeater> will generate the <tr> rows for us.
            -->
            <div class="gridview-responsive">
                <asp:GridView ID="gvProducts" runat="server" 
                AutoGenerateColumns="true" 
                CssClass="table table-striped table-hover table-bordered"
                GridLines="None" 
                BorderStyle="None" />
            </div>
        </div>
    </form>
</body>
</html>